[
[    gamedefs.h
[    GAME SPECIFIC DEFINITIONS FOR
[           %1
[
[  generated by WinAGI
[


[******************   WORDS   ******************]
%tokens	"..\\words.tok" 


[******************   ITEMS   ******************]
%2

[******************   VARS   *******************]
[ reserved by interpreter:       0-26
[ general use variables:       21-219
[ room variables:             220-239
[ dynamic logic variables:    240-255
%3

[******************   FLAGS   ******************]
[ reserved by interpreter:   0-16, 20
[ general use flags:           21-219
[ room flags:                 220-239
[ dynamic logic flags:        240-255
%4

[*****************   OBJECTS   *****************]
[ reserved by interpreter: 0
[ maximum object number: %5
%6

[******************   VIEWS   ******************]
%7

[******************   OTHER   ******************]
[ includes controllers, strings, words, as well
[ as unidentified views and objects
%8
